config/routes.rb
Rails.application.routes.draw do
  resources :alunos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/aluno.rb
class Aluno < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: %i[ show edit update destroy ]

  # GET /alunos or /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1 or /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos or /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: "Aluno was successfully created." }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1 or /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: "Aluno was successfully updated." }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1 or /alunos/1.json
  def destroy
    @aluno.destroy!

    respond_to do |format|
      format.html { redirect_to alunos_path, status: :see_other, notice: "Aluno was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def aluno_params
      params.expect(aluno: [ :nome, :idade, :cpf, :telefone, :email, :data_nascimento, :endereco, :observacao, :status ])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alunos/_aluno.html.erb
<div id="<%= dom_id aluno %>">
  <p>
    <strong>Nome:</strong>
    <%= aluno.nome %>
  </p>

  <p>
    <strong>Idade:</strong>
    <%= aluno.idade %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= aluno.cpf %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= aluno.telefone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= aluno.email %>
  </p>

  <p>
    <strong>Data nascimento:</strong>
    <%= aluno.data_nascimento %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= aluno.endereco %>
  </p>

  <p>
    <strong>Observacao:</strong>
    <%= aluno.observacao %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= aluno.status %>
  </p>

</div>

app/views/alunos/_form.html.erb
<%= form_with(model: aluno) do |form| %>
  <% if aluno.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
        <% aluno.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :idade, style: "display: block" %>
    <%= form.number_field :idade %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :data_nascimento, style: "display: block" %>
    <%= form.date_field :data_nascimento %>
  </div>

  <div>
    <%= form.label :endereco, style: "display: block" %>
    <%= form.textarea :endereco %>
  </div>

  <div>
    <%= form.label :observacao, style: "display: block" %>
    <%= form.textarea :observacao %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.checkbox :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<% content_for :title, "Editing aluno" %>

<h1>Editing aluno</h1>

<%= render "form", aluno: @aluno %>

<br>

<div>
  <%= link_to "Show this aluno", @aluno %> |
  <%= link_to "Back to alunos", alunos_path %>
</div>

app/views/alunos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Alunos" %>

<h1>Alunos</h1>

<div id="alunos">
  <% @alunos.each do |aluno| %>
    <%= render aluno %>
    <p>
      <%= link_to "Show this aluno", aluno %>
    </p>
  <% end %>
</div>

<%= link_to "New aluno", new_aluno_path %>

app/views/alunos/new.html.erb
<% content_for :title, "New aluno" %>

<h1>New aluno</h1>

<%= render "form", aluno: @aluno %>

<br>

<div>
  <%= link_to "Back to alunos", alunos_path %>
</div>

app/views/alunos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @aluno %>

<div>
  <%= link_to "Edit this aluno", edit_aluno_path(@aluno) %> |
  <%= link_to "Back to alunos", alunos_path %>

  <%= button_to "Destroy this aluno", @aluno, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Escola Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>